import { HumanEntry } from './types';

export const INITIAL_HUMAN_ENTRIES: HumanEntry[] = [
  {
    id: 'class-1',
    name: '김나연',
    nickname: '눈웃음녀',
    rarity: '전설',
    representativeTrait: '항상 웃고있는 아름다운 눈웃음',
    observation: '항상 볼 때마다 밝고 환하게 웃고 있음.',
    precaution: '눈웃음이 이쁘니 깊게 빠져들지 않도록 각별히 안구 관리에 주의하자.',
    achievement: '',
    stats: {
      sociability: 60,
      energy: 10,
      responsibility: 70,
      laughter: 100,
      alcohol: 90,
      silence: 70,
      humor: 0,
      indifference: 60,
    },
    imageUrl: 'Smile',
    createdAt: '2026-06-14T00:01:00.000Z',
  },
  {
    id: 'class-2',
    name: '김도현',
    nickname: '배구진심남',
    rarity: '일반',
    representativeTrait: '투박하지만 확실한 서비스 정신',
    observation: '주변 사람들을 뒤에서 조용하고 꼼꼼하게 잘 챙겨주지만 성격이나 말투가 약간 투박함.',
    precaution: '도현이에게 뜬금없는 개그를 시도하면 분위기가 크게 무안해질 수 있으니 밀고 당기기 필요.',
    achievement: 'MT 관리부의 영원한 구원투수이자 대들보, G.O.A.T.',
    stats: {
      sociability: 40,
      energy: 90,
      responsibility: 100,
      laughter: 30,
      alcohol: 80,
      silence: 90,
      humor: 0,
      indifference: 60,
    },
    imageUrl: 'Shield',
    createdAt: '2026-06-14T00:02:00.000Z',
  },
  {
    id: 'class-3',
    name: '김성민',
    nickname: '웨이터',
    rarity: '고급',
    representativeTrait: '소리없이 챙겨주는 버스 요정',
    observation: '조별 과제 시 간혹 팀원 버스를 타는 경향이 감지되나, 뒤에서는 묵묵히 하나하나 잘 챙겨줌.',
    precaution: '과제 분담표 작성 기간 도래 시 집중적으로 밀착 마크 필요.',
    achievement: '웨이터 (명예 칭호 획득)',
    stats: {
      sociability: 10,
      energy: 80,
      responsibility: 100,
      laughter: 10,
      alcohol: 90,
      silence: 100,
      humor: 0,
      indifference: 80,
    },
    imageUrl: 'Coffee',
    createdAt: '2026-06-14T00:03:00.000Z',
  },
  {
    id: 'class-4',
    name: '김수경',
    nickname: '탈색녀',
    rarity: '고급',
    representativeTrait: '빈티지 감성과 연세빵 콜렉터',
    observation: '클래식하고 오리지널리티 가득한 빈티지 패션을 좋아하며 특히 크림 가득한 연세빵 시식을 선호함.',
    precaution: '배고플 때 에너지 레벨이 급감하므로 마주치기 전 주머니에 연세빵을 지참하여 굶기지 말 것.',
    achievement: '',
    stats: {
      sociability: 80,
      energy: 70,
      responsibility: 70,
      laughter: 80,
      alcohol: 50,
      silence: 10,
      humor: 70,
      indifference: 70,
    },
    imageUrl: 'Sparkles',
    createdAt: '2026-06-14T00:04:00.000Z',
  },
  {
    id: 'class-5',
    name: '김승언',
    nickname: '배드민턴녀',
    rarity: '일반',
    representativeTrait: '과일 귀신 소프트 홈 프로텍터',
    observation: '방과 후에는 집 밖을 나서지 않는 안락한 홈 지향형 인물이자, 상상을 초월하는 수준의 과일 귀신.',
    precaution: '말씨를 항상 예쁘고 고운 언어로 대칭해야 긍정적 시너지를 유지 가능.',
    achievement: '',
    stats: {
      sociability: 50,
      energy: 80,
      responsibility: 70,
      laughter: 80,
      alcohol: 30,
      silence: 50,
      humor: 80,
      indifference: 40,
    },
    imageUrl: 'Zap',
    createdAt: '2026-06-14T00:05:00.000Z',
  },
  {
    id: 'class-6',
    name: '김주빈',
    nickname: '예(픈여자)미새',
    rarity: '전설',
    representativeTrait: '나이를 초월하는 솔직한 선망',
    observation: '자신을 유독 편안하고 친숙하게 대해주는 외모가 빼어난 이성이 불변의 이상형 목록 1순위.',
    precaution: '인간관계 확장을 위해 지체 없이 훌륭한 여자 소개 스케줄(여소)을 지속 수급할 것.',
    achievement: '예쁜 이성 대상이라면 최대 서른 살 나이대까지도 전부 커버 가능하다는 극강 심리 보유.',
    stats: {
      sociability: 40,
      energy: 50,
      responsibility: 70,
      laughter: 70,
      alcohol: 60,
      silence: 80,
      humor: 30,
      indifference: 20,
    },
    imageUrl: 'Heart',
    createdAt: '2026-06-14T00:06:00.000Z',
  },
  {
    id: 'class-7',
    name: '김지온',
    nickname: '포뇨',
    rarity: '희귀',
    representativeTrait: '볼 빨간 귀소 본능의 아이콘',
    observation: '특유의 볼 빨갛고 동글동글한 모션을 뽐내며, 방과 후나 매 틈새 시간마다 은밀하고 빠르게 집으로 도망침.',
    precaution: '본능적 귀가 기도를 인위적으로 방해하거나 도중에 붙잡아 두지 말아야 함.',
    achievement: '',
    stats: {
      sociability: 60,
      energy: 70,
      responsibility: 70,
      laughter: 80,
      alcohol: 80,
      silence: 40,
      humor: 50,
      indifference: 40,
    },
    imageUrl: 'Flame',
    createdAt: '2026-06-14T00:07:00.000Z',
  },
  {
    id: 'class-8',
    name: '김태린',
    nickname: '배구진심녀',
    rarity: '일반',
    representativeTrait: '코트 위 빽어택 서사 요정',
    observation: '네트 앞 빽어택 스매시에 극단적으로 몰입하며, 일상에서 게시하는 소셜 스토리가 유독 배꼽 빠지게 웃김.',
    precaution: '머리 염색 가동 주기에 관한 코멘트나 뿌리 염색(뿌염) 강제 권유는 기피할 것.',
    achievement: '',
    stats: {
      sociability: 60,
      energy: 70,
      responsibility: 70,
      laughter: 70,
      alcohol: 40,
      silence: 40,
      humor: 20,
      indifference: 50,
    },
    imageUrl: 'Compass',
    createdAt: '2026-06-14T00:08:00.000Z',
  },
  {
    id: 'class-9',
    name: '김태은',
    nickname: '술찌',
    rarity: '고급',
    representativeTrait: '알코올 미량 시한폭탄',
    observation: '최대 수용 캐파가 단 두 잔에 불과한 소박하고 앙증맞은 생체 회로 가동 메커니즘을 소유함.',
    precaution: '주량 초과 분기점에 도달하여 취기가 관측되면 불필요한 대화 없이 즉각 안전한 수면 침대로 인계할 것.',
    achievement: '',
    stats: {
      sociability: 20,
      energy: 50,
      responsibility: 70,
      laughter: 70,
      alcohol: 0,
      silence: 60,
      humor: 30,
      indifference: 50,
    },
    imageUrl: 'Moon',
    createdAt: '2026-06-14T00:09:00.000Z',
  },
  {
    id: 'class-10',
    name: '김하연',
    nickname: '술진심녀',
    rarity: '일반',
    representativeTrait: '밤샘 전우형 드링크 메이트',
    observation: '풍류와 액체를 매우 좋아하며 신선하고 화끈한 무드를 온몸으로 마음껏 즐길 준비가 언제든 완비됨.',
    precaution: '외로운 음주 고행길이 되지 않도록 반드시 대등한 주량 전우를 구비하여 끝까지 동석해줄 것.',
    achievement: '',
    stats: {
      sociability: 60,
      energy: 80,
      responsibility: 70,
      laughter: 60,
      alcohol: 90,
      silence: 70,
      humor: 40,
      indifference: 70,
    },
    imageUrl: 'Beer',
    createdAt: '2026-06-14T00:10:00.000Z',
  },
  {
    id: 'class-11',
    name: '김하희',
    nickname: '우리반대표테토녀',
    rarity: '고급',
    representativeTrait: '투명하고 발랄한 취함 주크박스',
    observation: '대표적인 취함 코어를 지니고 있어 감정과 상태 변화가 이마와 눈매를 아우르는 얼굴 전체 구도에 즉각 반영됨.',
    precaution: '농담으로든 장난으로든 술잔 러시 배틀 요청을 먼저 투척하면 극구 사양하는 미덕을 지녀라.',
    achievement: '치명적이고 처참한 다수의 로맨스 전장 소멸(썸붕) 기록 다량 누적.',
    stats: {
      sociability: 70,
      energy: 60,
      responsibility: 70,
      laughter: 60,
      alcohol: 30,
      silence: 40,
      humor: 90,
      indifference: 50,
    },
    imageUrl: 'Sparkles',
    createdAt: '2026-06-14T00:11:00.000Z',
  },
  {
    id: 'class-12',
    name: '남윤호',
    nickname: '우리반대표에겐남',
    rarity: '희귀',
    representativeTrait: '아이스 뽕따 소다 러버',
    observation: '남들이 전부 향긋하고 시원한 복숭아 아이스티를 수혈할 무렵, 흔들림 없이 푸근한 뽕따맛소다 팩 음료만 독식함.',
    precaution: '옆자리 친우 이승민 오빠와의 개그력 데시벨을 함부로 상호 비교 평가하지 않는 편이 이로움.',
    achievement: '친화력 10/10에 근접하는 인싸형 도약 노력이 가히 우주급 평준화 달성 점수를 획득함.',
    stats: {
      sociability: 100,
      energy: 70,
      responsibility: 90,
      laughter: 80,
      alcohol: 20,
      silence: 20,
      humor: 10,
      indifference: 30,
    },
    imageUrl: 'Crown',
    createdAt: '2026-06-14T00:12:00.000Z',
  },
  {
    id: 'class-13',
    name: '송현서',
    nickname: '갓생러',
    rarity: '전설',
    representativeTrait: '걸어 다니는 지식 도서관',
    observation: '강의 시간 집중도가 극상이며, 어려운 질문이나 학업 관련 애로사항을 문의하면 막힘없이 쾌적한 피드백을 안내해 줌.',
    precaution: '송현서의 고집중 공부 루틴을 인위적으로 해치지 않도록 적절한 도를 유지하자.',
    achievement: '학과 수료 기준 상위 고득점 달성자 유력 후보.',
    stats: {
      sociability: 60,
      energy: 60,
      responsibility: 70,
      laughter: 50,
      alcohol: 40,
      silence: 60,
      humor: 30,
      indifference: 70,
    },
    imageUrl: 'Flame',
    createdAt: '2026-06-14T00:13:00.000Z',
  },
  {
    id: 'class-14',
    name: '심지연',
    nickname: '이마미녀',
    rarity: '일반',
    representativeTrait: '티격태격 오누이 기획자',
    observation: '사교성이 발군이며, 만나기만 하면 김도현 대원과 티격태격하며 웃음벨 오누이 스파크를 수시로 방출함.',
    precaution: '김도현과의 찰진 설투 중 격정 구간에 휘둘려 중간에 함부로 엮이지 말 것.',
    achievement: '모두가 안전하게 취식하고 즐길 수 있는 MT 관리부 전설의 사령관 취득.',
    stats: {
      sociability: 40,
      energy: 80,
      responsibility: 80,
      laughter: 60,
      alcohol: 50,
      silence: 70,
      humor: 20,
      indifference: 60,
    },
    imageUrl: 'Compass',
    createdAt: '2026-06-14T00:14:00.000Z',
  },
  {
    id: 'class-15',
    name: '양가인',
    nickname: '주당',
    rarity: '일반',
    representativeTrait: '영원한 불사의 간 소유자',
    observation: '수많은 술자리가 무장해제당하고 숙취 해소 음료를 외칠 때도 유일무이하게 무너지지 않는 불사의 취식 주량을 소유함.',
    precaution: '절대로 쓸데없는 객기로 가인 대원에게 만취 상태의 술 배틀 챌린지를 호기롭게 도전하지 마시오.',
    achievement: '학과 개설 이래 역사상 취한 모습을 전우 단 한 사람에게도 발각 당하지 않은 영생의 주당.',
    stats: {
      sociability: 40,
      energy: 60,
      responsibility: 80,
      laughter: 60,
      alcohol: 100,
      silence: 70,
      humor: 30,
      indifference: 50,
    },
    imageUrl: 'Beer',
    createdAt: '2026-06-14T00:15:00.000Z',
  },
  {
    id: 'class-16',
    name: '우정민',
    nickname: '과대',
    rarity: '일반',
    representativeTrait: '1학기 든든하고 투명한 기둥',
    observation: '책임감과 위기 대처력이 우수하여 1학기 초반 학급 정렬 및 크고 작은 잡음 해결에 열성적으로 공헌함.',
    precaution: '음주 수치가 극한으로 차올라 만취 상태에 진입할 경우 솔직하고 거친 단공이 튀어나올 수 있으니 감상 보호 조치 주의.',
    achievement: '역사적인 제 1학기 초대 과대 임금 단독 추대 및 연착륙 성공.',
    stats: {
      sociability: 70,
      energy: 60,
      responsibility: 70,
      laughter: 70,
      alcohol: 40,
      silence: 20,
      humor: 40,
      indifference: 70,
    },
    imageUrl: 'Crown',
    createdAt: '2026-06-14T00:16:00.000Z',
  },
  {
    id: 'class-18',
    name: '육예주',
    nickname: '예또취',
    rarity: '일반',
    representativeTrait: '취중 김치찌개 테러와 눈 세레머니',
    observation: '술자리 흥이 발작하면 조절 능력이 저하되어 동문 주현 오빠의 소중한 명품 바지에 김치찌개를 직격 사출하는 치명타를 터뜨림.',
    precaution: '취기가 감지되면 반사 행동으로 안구가 평소보다 약 4배가량 기하급수적으로 확장되므로 안면 인식 주의 개시.',
    achievement: '공포와 순수가 공존하는 취중 눈 크게 뜨기 대기록 통산 19,875,645회 대기록 갱신 중.',
    stats: {
      sociability: 20,
      energy: 40,
      responsibility: 70,
      laughter: 60,
      alcohol: 20,
      silence: 100,
      humor: 30,
      indifference: 50,
    },
    imageUrl: 'Sparkles',
    createdAt: '2026-06-14T00:18:00.000Z',
  },
  {
    id: 'class-19',
    name: '윤세미',
    nickname: '우정민반쪽',
    rarity: '일반',
    representativeTrait: '국제 미팅 훈련 요원',
    observation: '캠퍼스 안팎을 불문하고 각종 다자간 사교 미팅 행사에 단골 정찰 대원으로 신속히 파견 및 출격함.',
    precaution: '해 질 무렵 과방 정규 주점에서 맥주 레이저 가동 시, 마음대로 옆 과방 타인 영역으로 월경하는 이동을 적극 봉쇄 바람.',
    achievement: '',
    stats: {
      sociability: 30,
      energy: 40,
      responsibility: 70,
      laughter: 50,
      alcohol: 10,
      silence: 60,
      humor: 20,
      indifference: 70,
    },
    imageUrl: 'Heart',
    createdAt: '2026-06-14T00:19:00.000Z',
  },
  {
    id: 'class-20',
    name: '이성순',
    nickname: '배구진심녀22',
    rarity: '일반',
    representativeTrait: '부상 투혼의 불꽃 마라토너',
    observation: '스포츠 활동에 전신을 아끼지 않아 무릎과 발목 등에 지속적으로 영광의 파스 훈장을 보존 중인 정열의 스포츠 대원.',
    precaution: '한시도 몸을 가만 두지 않으려 하니 걷기나 스트레칭 시 낙치 부상을 예방할 수 있게 밀접 안면 보호 요망.',
    achievement: '학기 우수 도우미 부과대 칭호 획득.',
    stats: {
      sociability: 30,
      energy: 80,
      responsibility: 80,
      laughter: 50,
      alcohol: 10,
      silence: 60,
      humor: 10,
      indifference: 30,
    },
    imageUrl: 'Shield',
    createdAt: '2026-06-14T00:20:00.000Z',
  },
  {
    id: 'class-21',
    name: '이승민',
    nickname: '두부게임남',
    rarity: '전설',
    representativeTrait: '숨 쉬듯 빵빵 터지는 인간 스마일리',
    observation: '존재 자체가 한 편의 시트콤 시리즈 시나리오 같으며 특별한 입담을 쓰지 않고 은은히 바라만 보아도 그냥 호쾌한 실소가 터짐.',
    precaution: '공공장소나 엄숙한 지하철 내에서 눈을 똑바로 조우할 시 강력한 조롱 및 소외 피해를 입을 수 있음.',
    achievement: '지하철 플랫폼 통로 마주칩 상황에서 모르는 척 가던 길 가기 938,371회 아시아 신기록 보유.',
    stats: {
      sociability: 20,
      energy: 40,
      responsibility: 80,
      laughter: 40,
      alcohol: 60,
      silence: 80,
      humor: 100,
      indifference: 90,
    },
    imageUrl: 'Zap',
    createdAt: '2026-06-14T00:21:00.000Z',
  },
  {
    id: 'class-22',
    name: '이예담',
    nickname: '바라보컬',
    rarity: '일반',
    representativeTrait: '6AM 새벽 밤샘 노래벌레',
    observation: '완벽한 생체 야간 역전 회로 세팅을 갖췄으며, 동틀 녘 아침 서서히 스르륵 커튼을 치며 숙면에 안착하는 올빼미 생활의 수장.',
    precaution: '오전 8-9시 강의 진행 시 실시간 혼미 현상이 관찰될 가능성이 농후하니 전화 알람 비상대기 가동.',
    achievement: '정상 등교 타임 무단 지각하기 누적 738,592회 돌파 기염.',
    stats: {
      sociability: 20,
      energy: 40,
      responsibility: 70,
      laughter: 50,
      alcohol: 20,
      silence: 80,
      humor: 10,
      indifference: 80,
    },
    imageUrl: 'Moon',
    createdAt: '2026-06-14T00:22:00.000Z',
  },
  {
    id: 'class-23',
    name: '이의림',
    nickname: '빨간머리녀',
    rarity: '일반',
    representativeTrait: '강철 가면 뒤의 감수성 도토리',
    observation: '상심이 큰 속마음을 타인에게 노출하지 않으려 겉으로는 쿨한 척 도도히 걷지만, 실상은 아기 고양이처럼 여리고 마음이 고움.',
    precaution: '앤드류 첫 강연 타임 때 머리 안 감고 수줍게 썼던 스냅백 모자가 불시에 압수(Take Off)되는 아픔이 기억되고 있음.',
    achievement: '연애 노선 도중 남자친구에게 자아성찰 급 대공습 수치성 공격 피격 완료.',
    stats: {
      sociability: 60,
      energy: 40,
      responsibility: 70,
      laughter: 50,
      alcohol: 40,
      silence: 50,
      humor: 90,
      indifference: 40,
    },
    imageUrl: 'Flame',
    createdAt: '2026-06-14T00:23:00.000Z',
  },
  {
    id: 'class-24',
    name: '이정민',
    nickname: '야구진심녀',
    rarity: '희귀',
    representativeTrait: '영혼의 소맥 황금 비율 제조기',
    observation: '틈만 나면 부리나케 고풍스러운 안방 본가로 신속 공간 이동한 후 마르지 않는 술지옥 주막을 자발적으로 개설함.',
    precaution: '정민 주도 하에 맥주를 개봉할 시, 톡 쏘고 황홀무쌍한 정밀 비율 황금 소맥을 무조건 영접하는 기틀 마련 필수.',
    achievement: '',
    stats: {
      sociability: 30,
      energy: 20,
      responsibility: 70,
      laughter: 40,
      alcohol: 70,
      silence: 70,
      humor: 30,
      indifference: 40,
    },
    imageUrl: 'Compass',
    createdAt: '2026-06-14T00:24:00.000Z',
  },
  {
    id: 'class-25',
    name: '이호원',
    nickname: '삼촌',
    rarity: '전설',
    representativeTrait: '삼십분 지각 보스 자이언트',
    observation: '멀리서도 헤드라이트처럼 홀로 눈에 띄는 최장신 자이언트 골격을 가졌으며 모든 조원 대원들을 삼촌처럼 뜨겁게 포용해 줌.',
    precaution: '주량이 베일에 가려진 무제한 수수께끼형 개체이므로, 호기로운 동석 시에는 필히 귀가 택시 예비비를 다수 비축할 것.',
    achievement: '자칭 타칭 극기 모임인 등산 패밀리 집결 시간에 매너 타임 상습 30분 초과 지각 달성.',
    stats: {
      sociability: 70,
      energy: 80,
      responsibility: 70,
      laughter: 30,
      alcohol: 80,
      silence: 30,
      humor: 10,
      indifference: 20,
    },
    imageUrl: 'Crown',
    createdAt: '2026-06-14T00:25:00.000Z',
  },
  {
    id: 'class-26',
    name: '임소린',
    nickname: '쿼카',
    rarity: '희귀',
    representativeTrait: '에이블리 최상위 서클 소비 대장',
    observation: '마주할 때마다 항상 바쁘게 각종 생계 전선 파트타임 아르바이트를 클리어하는 억척스럽고 사랑스러운 쿼카상 인물.',
    precaution: '알바 수당이 통장에 실시간 수혈되는 시간대에는 쇼핑 애플리케이션으로 수만 원 단위 정밀 격파 작업 개시 주의.',
    achievement: '쇼핑앱 에이블리(Aebly) 명예 장인 등급, 영롱한 다이아 VIP 신격 위치 수성.',
    stats: {
      sociability: 60,
      energy: 20,
      responsibility: 70,
      laughter: 40,
      alcohol: 10,
      silence: 50,
      humor: 20,
      indifference: 30,
    },
    imageUrl: 'Heart',
    createdAt: '2026-06-14T00:26:00.000Z',
  },
  {
    id: 'class-27',
    name: '조민성',
    nickname: '연하같은연상남',
    rarity: '전설',
    representativeTrait: '100점 만점 데이터베이스 준비 요정',
    observation: '차분하고 정적인 바이브와 더불어, 약속 시간 조율이나 데이트 코디 스케줄을 미리 소밀하고 완벽하게 파악해놓는 꼼꼼함의 가풍.',
    precaution: '꼼꼼하다가도 돌발적인 일탈 유혹에 흔들릴 수 있으며, 가끔 예고 없이 가증스러운 자체휴학 버튼을 폭격함.',
    achievement: '누구도 제어할 수 없는 전설의 학교 탈출용 필살기 "자체휴강" n회 연속 기록 완결.',
    stats: {
      sociability: 10,
      energy: 20,
      responsibility: 70,
      laughter: 30,
      alcohol: 40,
      silence: 90,
      humor: 90,
      indifference: 10,
    },
    imageUrl: 'Coffee',
    createdAt: '2026-06-14T00:27:00.000Z',
  },
  {
    id: 'class-28',
    name: '조은지',
    nickname: '술중독',
    rarity: '일반',
    representativeTrait: '갈망의 에탄올 영혼 소환사',
    observation: '이른 아침 강연 오프닝 타이밍부터 깊은 노을빛 하교 루트까지 언제 어디서나 목에 차갑고 구수한 액체 한 잔을 넘기기를 고대하는 갈망의 화신.',
    precaution: '알코올 미충전 타임이 길어질 경우 갑작스러운 전공 수포 선언과 함께 폭탄 드랍 선언을 날릴 여지 다분.',
    achievement: '일요일 오후 같은 차분하고 무던한 혜안으로 수강 신청 수업 깔끔하게 던지기(드랍) 권위자.',
    stats: {
      sociability: 30,
      energy: 50,
      responsibility: 70,
      laughter: 20,
      alcohol: 30,
      silence: 80,
      humor: 20,
      indifference: 40,
    },
    imageUrl: 'Beer',
    createdAt: '2026-06-14T00:28:00.000Z',
  },
  {
    id: 'class-29',
    name: '주시연',
    nickname: '스파이',
    rarity: '전설',
    representativeTrait: '얼굴 한 폭 빨간 수줍음의 수호자',
    observation: '말수가 매우 극단적으로 고요하여 학기 초 기밀 첩보 요원(스파이)으로 오해받았으나 한 발짝 다가가면 유독 여리고 치명적으로 귀염터짐.',
    precaution: '귀여움에 매료되어 먼저 다가가 갑작스러운 고열량 롱 대화를 시도하면 볼때기가 붉은 홍당무 색상으로 변색되니 조언 요망.',
    achievement: '동료 주동자들의 시선을 전부 묵언 스킬 하나로 완전히 진공 청소 및 봉쇄 완료.',
    stats: {
      sociability: 0,
      energy: 20,
      responsibility: 70,
      laughter: 40,
      alcohol: 60,
      silence: 100,
      humor: 0,
      indifference: 70,
    },
    imageUrl: 'Moon',
    createdAt: '2026-06-14T00:29:00.000Z',
  },
  {
    id: 'class-30',
    name: '지시연',
    nickname: '공주님',
    rarity: '고급',
    representativeTrait: '콘서트 순회형 오타쿠 댕댕이',
    observation: '포근하고 방실거리는 말티즈형 소형견 포지션을 고행하며, 스마트폰 갤러리는 좋아하는 케이팝 아이돌 피사체로 가득 차 있음.',
    precaution: '돌발 티케팅 타임이나 굿즈 팝업 발매가 다가오면 순간적으로 우주적 텐션을 분출하니 심장 보호 장비 준비.',
    achievement: '달력을 빽빽하게 빼곡히 도장 깨는 월간 아이돌 내한 콘서트 전 횟수 연속 완전 정복 달성.',
    stats: {
      sociability: 40,
      energy: 10,
      responsibility: 70,
      laughter: 20,
      alcohol: 40,
      silence: 60,
      humor: 30,
      indifference: 40,
    },
    imageUrl: 'Heart',
    createdAt: '2026-06-14T00:30:00.000Z',
  },
  {
    id: 'class-31',
    name: '최윤서',
    nickname: '동키',
    rarity: '일반',
    representativeTrait: '컹컹 사운드 사이다 리액터',
    observation: '주변 시선과 다른 사람들 동향을 끊임없이 살피며 소심하게 눈치를 보나, 한번 신나면 웃음 주체 불능 영역에 도달함.',
    precaution: '웃음 데시벨이 고공분투하여 빵 터질 시 콧구멍에서 특유의 "컹컹!" 하는 희귀 사운드가 자동 송출되므로 부드럽게 무한 맞대응 할 것.',
    achievement: '동기 친우들의 극도 집중적인 애정 장난 및 귀여운 사설 조롱 놀이터로써 은근히 행복한 기여 장인 등극.',
    stats: {
      sociability: 30,
      energy: 50,
      responsibility: 70,
      laughter: 60,
      alcohol: 20,
      silence: 80,
      humor: 80,
      indifference: 40,
    },
    imageUrl: 'Smile',
    createdAt: '2026-06-14T00:31:00.000Z',
  },
  {
    id: 'class-32',
    name: '최지원',
    nickname: '자칭 줏대녀',
    rarity: '일반',
    representativeTrait: '크라운 휴지 무덤 메이커',
    observation: '스스로는 영롱하고 단단한 철학을 지닌 자칭 줏대 있는 지존녀라 외치나, 실제로는 마음이 한없이 여리고 귀가 얇은 백지장 멘탈녀.',
    precaution: '마치 바람에 한들거리는 코스모스 같으니 상처를 주지 않고 옆에서 단단한 대들보처럼 항상 부축하고 호응해줄 것.',
    achievement: '크라운 맥주 매장에서 감격에 빠져 쏟은 미풍 눈물과 땀방울을 닦기 위해 활용한 소용돌이 흰 휴지만 도합 29,865개 돌파.',
    stats: {
      sociability: 80,
      energy: 70,
      responsibility: 70,
      laughter: 70,
      alcohol: 80,
      silence: 60,
      humor: 40,
      indifference: 30,
    },
    imageUrl: 'Zap',
    createdAt: '2026-06-14T00:32:00.000Z',
  },
];
